[package]
name = "tedpinkerton-ca"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.6", features = ["router"] }
dioxus-sdk = { version = "0.6", features = ["storage", "system_theme"] }
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
